export const endpoints = {
  auth: {
    login: "/api/auth/login/",
    refresh: "/api/auth/refresh/",
  },
  me: "/api/me/",
  users: "/api/users/",
  hr: {
    departments: "/api/departments/",
    jobTitles: "/api/job-titles/",
    employees: "/api/employees/",
    employee: (id: number) => `/api/employees/${id}/`,
    employeeDocuments: (employeeId: number) => `/api/employees/${employeeId}/documents/`,
    documentDownload: (id: number) => `/api/documents/${id}/download/`,
    documentDelete: (id: number) => `/api/documents/${id}/`,
    department: (id: number) => `/api/departments/${id}/`,
    jobTitle: (id: number) => `/api/job-titles/${id}/`,
    attendanceRecords: "/api/attendance/records/",
    attendanceCheckIn: "/api/attendance/check-in/",
    attendanceCheckOut: "/api/attendance/check-out/",
    attendanceMy: "/api/attendance/my/",
    attendanceQrGenerate: "/api/attendance/qr/generate/",
    leaveTypes: "/api/leaves/types/",
    leaveBalances: "/api/leaves/balances/",
    leaveBalanceMy: "/api/leaves/balances/my/",
    leaveRequestsMy: "/api/leaves/requests/my/",
    leaveRequests: "/api/leaves/requests/",
    leaveRequestCancel: (id: number) => `/api/leaves/requests/${id}/cancel/`,
    leaveApprovalsInbox: "/api/leaves/approvals/inbox/",
    leaveRequestApprove: (id: number) => `/api/leaves/requests/${id}/approve/`,
    leaveRequestReject: (id: number) => `/api/leaves/requests/${id}/reject/`,
    policies: "/api/policies/",
    hrActions: "/api/actions/",
  },
};  