export const endpoints = {
  auth: {
    login: "/api/auth/login/",
    refresh: "/api/auth/refresh/",
  },
  me: "/api/me/",
  users: "/api/users/",
  hr: {
    departments: "/api/departments/",
    jobTitles: "/api/job-titles/",
    employees: "/api/employees/",
    employee: (id: number) => `/api/employees/${id}/`,
    employeeDocuments: (employeeId: number) => `/api/employees/${employeeId}/documents/`,
    documentDownload: (id: number) => `/api/documents/${id}/download/`,
    documentDelete: (id: number) => `/api/documents/${id}/`,
    department: (id: number) => `/api/departments/${id}/`,
    jobTitle: (id: number) => `/api/job-titles/${id}/`,
    attendanceRecords: "/api/attendance/records/",
    attendanceCheckIn: "/api/attendance/check-in/",
    attendanceCheckOut: "/api/attendance/check-out/",
    attendanceMy: "/api/attendance/my/",
    attendanceQrGenerate: "/api/attendance/qr/generate/",
    leaveTypes: "/api/leaves/types/",
    leaveBalances: "/api/leaves/balances/",
    leaveBalanceMy: "/api/leaves/balances/my/",
    leaveRequestsMy: "/api/leaves/requests/my/",
    leaveRequests: "/api/leaves/requests/",
    leaveRequestCancel: (id: number) => `/api/leaves/requests/${id}/cancel/`,
    leaveApprovalsInbox: "/api/leaves/approvals/inbox/",
    leaveRequestApprove: (id: number) => `/api/leaves/requests/${id}/approve/`,
    leaveRequestReject: (id: number) => `/api/leaves/requests/${id}/reject/`,
    policies: "/api/policies/",
    hrActions: "/api/actions/",
    payrollPeriods: "/api/payroll/periods/",
    payrollPeriodGenerate: (id: number) => `/api/payroll/periods/${id}/generate/`,
    payrollPeriodRuns: (id: number) => `/api/payroll/periods/${id}/runs/`,
    payrollPeriodLock: (id: number) => `/api/payroll/periods/${id}/lock/`,
    payrollRun: (id: number) => `/api/payroll/runs/${id}/`,
    payrollRunPayslip: (id: number) => `/api/payroll/runs/${id}/payslip.pdf`,
  },
  accounting: {
    accounts: "/api/accounting/accounts/",
    account: (id: number) => `/api/accounting/accounts/${id}/`,
    mappings: "/api/accounting/mappings/",
    mapping: (id: number) => `/api/accounting/mappings/${id}/`,
    mappingsBulkSet: "/api/accounting/mappings/bulk-set/",
    costCenters: "/api/accounting/cost-centers/",    
    costCenter: (id: number) => `/api/accounting/cost-centers/${id}/`,
    applyTemplate: "/api/accounting/coa/apply-template/",
    journalEntries: "/api/accounting/journal-entries/",
    journalEntry: (id: number) => `/api/accounting/journal-entries/${id}/`,
    expenses: "/api/expenses/",
    expense: (id: number) => `/api/expenses/${id}/`,
    expenseApprove: (id: number) => `/api/expenses/${id}/approve/`,
    expenseAttachments: (id: number) => `/api/expenses/${id}/attachments/`,
  },
};