# Generated by Django 5.2.10 on 2026-01-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journal_entry_and_lines'),
        ('core', '0003_auditlog'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalline',
            name='journal_line_single_sided_amount',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__company_7e9397_idx',
            old_name='accounting_company_2f9f35_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__company_6ba722_idx',
            old_name='accounting_company_2451e7_idx',
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='journal_line_single_sided_amount'),
        ),
    ]
