# Generated by Django 5.2.10 on 2026-01-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_accountmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('payroll', 'Payroll'), ('payroll_period', 'Payroll Period'), ('expense', 'Expense'), ('adjustment', 'Adjustment')], default='manual', max_length=32),
        ),
    ]
