# Generated by Django 5.2.10 on 2026-02-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_alter_journalentry_reference_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "credit_limit",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("payment_terms_days", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="customers",
                        to="core.company",
                    ),
                ),
            ],
            options={},
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("company", "code"),
                name="unique_customer_code_per_company",
            ),
        ),
    ]