# Generated by Django 5.2.10 on 2026-01-22 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_alter_journalentry_reference_type_payment"),
        ("core", "0003_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("overdue_invoice", "Overdue Invoice"),
                            ("credit_limit", "Credit Limit"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.CharField(max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("high", "High")], max_length=16
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "type", "entity_id"),
                        name="unique_alert_per_company_entity",
                    )
                ],
            },
        ),
    ]