# Generated by Django 5.2.11 on 2026-02-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_catalogitem_stocktransaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountmapping",
            name="key",
            field=models.CharField(
                choices=[
                    ("ACCOUNTS_RECEIVABLE", "Accounts Receivable"),
                    ("SALES_REVENUE", "Sales Revenue"),
                    ("SALES_LIABILITY", "Sales Liability"),
                    ("SALES_COGS_EXPENSE", "Cost of Goods Sold"),
                    ("PAYROLL_SALARIES_EXPENSE", "Payroll Salaries Expense"),
                    ("PAYROLL_PAYABLE", "Payroll Payable"),
                    ("EXPENSE_DEFAULT_CASH", "Expense Default Cash"),
                    ("EXPENSE_DEFAULT_AP", "Expense Default AP"),
                ],
                max_length=64,
            ),
        ),
    ]