# Generated by Django 5.2.11 on 2026-02-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0012_alter_accountmapping_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="tax_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tax percentage applied to subtotal.",
                max_digits=5,
                null=True,
            ),
        ),
    ]