# Generated by Django 5.2.10 on 2026-01-20 22:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auditlog"),
        ("hr", "0004_leavetype_leaverequest_leavebalance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("late_over_minutes", "Late over minutes"),
                            ("late_count_over_period", "Late count over period"),
                            ("absent_count_over_period", "Absent count over period"),
                        ],
                        max_length=50,
                    ),
                ),
                ("threshold", models.PositiveIntegerField()),
                ("period_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[("warning", "Warning"), ("deduction", "Deduction")],
                        max_length=20,
                    ),
                ),
                (
                    "action_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HRAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[("warning", "Warning"), ("deduction", "Deduction")],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("reason", models.TextField()),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "attendance_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_actions",
                        to="hr.attendancerecord",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_actions",
                        to="hr.employee",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="hr.policyrule",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("attendance_record__isnull", False)),
                        fields=("company", "employee", "rule", "attendance_record"),
                        name="unique_hr_action_per_attendance",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("period_end__isnull", False),
                            ("period_start__isnull", False),
                        ),
                        fields=(
                            "company",
                            "employee",
                            "rule",
                            "period_start",
                            "period_end",
                        ),
                        name="unique_hr_action_per_period",
                    ),
                ],
            },
        ),
    ]