# Generated by Django 5.2.10 on 2026-01-28 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_loanadvance_payrollperiod_payrollrun_payrollline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr.shift",
            ),
        ),
    ]