# Generated by Django 5.2.10 on 2026-01-30 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_companyemailconfig'),
        ('hr', '0008_attendance_otp_and_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceotprequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company'),
        ),
    ]
