# Generated by Django 5.2.10 on 2026-01-31 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_companyemailconfig'),
        ('hr', '0011_salary_type_commission_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.company'),
        ),
    ]
