# Generated by Django 5.2.10 on 2026-02-01 06:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_ensure_payroll_period_period_type_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hraction',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=10),
        ),
    ]
