# Generated by Django 5.2.11 on 2026-02-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0018_salary_component_payroll_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeedocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("employee_file", "Employee File"),
                    ("contract", "Contract"),
                    ("invoice", "Invoice"),
                    ("other", "Other"),
                ],
                default="employee_file",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="linked_entity_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="linked_entity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("employee", "Employee"),
                    ("invoice", "Invoice"),
                    ("contract", "Contract"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="ocr_text",
            field=models.TextField(blank=True),
        ),
    ]