# Generated by Django 5.2.10 on 2026-01-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alerts_engine'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='alert_event_company',
            old_name='alert_event_company_status_date_idx',
        ),
    ]
