export const PERMISSION_CODES = [
  "users.view",
  "users.create",
  "users.edit",
  "users.delete",
  "users.reset_password",  
  "employees.*",
  "employees.view_team",
  "attendance.*",
  "attendance.view_team",
  "leaves.*",
  "accounting.*",
  "accounting.view",
  "accounting.manage_coa",
  "accounting.journal.view",
  "accounting.journal.post",  
  "accounting.reports.view",
  "expenses.*",  
  "expenses.view",
  "expenses.create",
  "expenses.approve",
  "invoices.*",  
  "customers.view",
  "customers.create",
  "customers.edit",
  "approvals.*",  
  "hr.departments.view",
  "hr.departments.create",
  "hr.departments.edit",
  "hr.departments.delete",
  "hr.job_titles.view",
  "hr.job_titles.create",
  "hr.job_titles.edit",
  "hr.job_titles.delete",
  "hr.employees.view",
  "hr.employees.create",
  "hr.employees.edit",
  "hr.employees.delete",
  "hr.documents.*",
  "hr.documents.view",
  "hr.documents.create",
  "hr.documents.delete",
  "hr.payroll.view",
  "hr.payroll.create",
  "hr.payroll.generate",
  "hr.payroll.lock",
  "hr.payroll.payslip",
  "hr.payroll.*",
  "analytics.alerts.view",
  "analytics.alerts.manage",
] as const;

export const ROLE_PERMISSIONS = {
  Admin: ["*"],
  HR: [
    "employees.*",
    "attendance.*",
    "leaves.*",
    "users.view",
    "hr.payroll.*",
  ],  
  Accountant: ["accounting.*", "expenses.*", "invoices.*", "customers.*"],
  Sales: ["customers.view"],  
  Manager: ["approvals.*", "attendance.view_team", "employees.view_team"],
} as const;

export type PermissionCode = (typeof PERMISSION_CODES)[number];
export type RoleName = keyof typeof ROLE_PERMISSIONS;