# Generated by Django 5.2.10 on 2026-01-28 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auditlog_after_auditlog_before_auditlog_ip_address_and_more"),
        ("hr", "0007_employee_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="attendance_qr_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="attendance_qr_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="attendance_qr_worksite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_qr_companies",
                to="hr.worksite",
            ),
        ),
    ]