# Generated by Django 5.2.11 on 2026-02-14 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_chatmessageattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                ("is_private", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="chatconversation",
            name="chat_conversation_distinct_participants",
        ),
        migrations.RemoveConstraint(
            model_name="chatconversation",
            name="unique_chat_conversation_pair",
        ),
        migrations.AlterField(
            model_name="chatconversation",
            name="participant_one",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_conversations_as_one",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chatconversation",
            name="participant_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_conversations_as_two",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatgroup",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_groups",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="chatgroup",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_chat_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation",
                to="core.chatgroup",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="core.chatgroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatconversation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("group__isnull", False),
                        ("participant_one__isnull", True),
                        ("participant_two__isnull", True),
                    ),
                    models.Q(
                        ("group__isnull", True),
                        ("participant_one__isnull", False),
                        ("participant_two__isnull", False),
                        models.Q(
                            ("participant_one", models.F("participant_two")),
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="chat_conversation_distinct_participants",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatconversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", True)),
                fields=("company", "participant_one", "participant_two"),
                name="unique_chat_conversation_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatconversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", False)),
                fields=("group",),
                name="unique_chat_group_conversation",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("group__isnull", False), ("recipient__isnull", True)),
                    models.Q(("group__isnull", True), ("recipient__isnull", False)),
                    _connector="OR",
                ),
                name="chat_message_direct_or_group",
            ),
        ),
        migrations.AddField(
            model_name="chatgroupmembership",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_chat_group_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatgroupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="core.chatgroup",
            ),
        ),
        migrations.AddField(
            model_name="chatgroupmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_group_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="chatgroup",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_chat_group_name_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatgroupmembership",
            constraint=models.UniqueConstraint(
                fields=("group", "user"), name="unique_chat_group_member"
            ),
        ),
    ]